/**:
  ros__parameters:
    use_sim_time: false
    cloud_topic: "/wamv_rise/livox/lidar"
    sensor_frame: "wamv_rise/livox_frame"
    world_frame: "wamv_rise/world"
    max_points: 2
    process_interval_sec: 2.0
    tf_timeout: 0.5
    tf_prefix: "wamv_rise"
    toll_service_name: "/wamv_rise/toLL"

    subscribe_topic: "local/feature_geo_points_sub"
    publish_topic: "navsatfix"
