/**:
  ros__parameters:
    # geopose_topic: '/wamv_rise/mvp_c2_commander/remote/id_4/geopose'
    geopose_topic: '/wamv_rise/odometry/geopose'

    usbl_topic: '/wamv_rise/usbl_data'
    modem_navsatfix_topic: '/wamv_rise/usbl/modem_navsatfix'
    world_frame: 'wamv_rise/world'
    # sensor2baselink_tf: [-0.14, -0.096718, -0.84, 0.0, 0.0, -0.349065844]
    sensor2baselink_tf: [-0.14, 0.0, -0.84, 0.0, 0.0, -0.349065844]
